### ISSUE TITLE
When Miner (claymore) responds with less than 2 lines, rig-monitorv2 crashes

### ISSUE THREAD

**Issue by tcsekhar** [rodneymo/rig-monitorv2#24]
Can you please add a try catch to the portion where you ignore the parsing of JSON error - when you receive the JSON from claymore miner?

**Comment by tcsekhar** [comment]
Here is the error:

INFO: 2018/05/30 15:42:58 claymore.go:142: Miner(claymore) response is 10 lines long.
panic: runtime error: index out of range

goroutine 23 [running]:
go-rig-monitor/miner.parseClaymoreOutputLine(0x10bd9f14, 0x10e71b00, 0x5e, 0x10bd9cac)
        /Users/ramf/go/src/go-rig-monitor/miner/claymore.go:230 +0x2304
go-rig-monitor/miner.(*RigConfig).LoadClaymmoreData(0x10a20ce0, 0x10a41f00, 0x0)
        /Users/ramf/go/src/go-rig-monitor/miner/claymore.go:150 +0x320
go-rig-monitor/miner.Monitor(0x10aa8040, 0x10a41f00)
        /Users/ramf/go/src/go-rig-monitor/miner/rig-monitor.go:28 +0x124
created by main.main
        /Users/ramf/go/src/go-rig-monitor/main.go:146 +0x93c

**Comment by rodneymo** [comment]
Hi,
Could you attach your config and a trace? To run a trace  use the -t flag

**Comment by tcsekhar** [comment]
Wow! You are amazing.

Thank you so much!


*Chandra Sekhar*
