### ISSUE TITLE
crashes due to claymore wrong output

### ISSUE THREAD

**Issue by rodneymo** [rodneymo/rig-monitorv2#34]
During the stability testing (>10 days) there was a crash due to claymore's html output not including the GPU spec lines. It's a rare occurrence, I have only seen it once. Here's the relevant part of the trace:

> INFO: 2018/06/08 02:57:52 claymore.go:141: Miner(claymore) response is 2 lines long.
TRACE: 2018/06/08 02:57:52 claymore.go:143: Miner(claymore) response from rig02:
 ETH - Total Speed: 133.281 Mh/s, Total Shares: 829, Rejected: 0, Time: 07:39
ETH: GPU0 28.059 Mh/s, GPU1 28.456 Mh/s, GPU2 28.435 Mh/s, GPU3 24.159 Mh/s, GPU4 24.173 Mh/s
TRACE: 2018/06/08 02:57:52 claymore.go:158: Claymore line to parse: ETH - Total Speed: 133.281 Mh/s, Total Shares: 829, Rejected: 0, Time: 07:39
panic: runtime error: index out of range

goroutine 15 [running]:
go-rig-monitor/miner.parseClaymoreOutputLine(0x1209bf14, 0x11ed8b00, 0x4c, 0x1209bc8c)
	/Users/ramf/go/src/go-rig-monitor/miner/claymore.go:261 +0x22bc
go-rig-monitor/miner.(*RigConfig).LoadClaymmoreData(0x11e64600, 0x11e13f80, 0x0)
	/Users/ramf/go/src/go-rig-monitor/miner/claymore.go:160 +0x490
go-rig-monitor/miner.Monitor(0x11e8c240, 0x11e13f80)

**Comment by rodneymo** [comment]
Fixed in both 2.2.2 (stable) and 2.3.d.5 (development) versions.
